Repository CExA-project/ddc, pull requests merged in 2024-05, with the labels that each got.

#433 Matrix classes doc
  include/ddc/kernels/splines/matrix.hpp
  include/ddc/kernels/splines/matrix_maker.hpp
  include/ddc/kernels/splines/matrix_sparse.hpp
Labels: documentation

#431 Splines small classes doc
  include/ddc/kernels/splines/deriv.hpp
  include/ddc/kernels/splines/ginkgo_executors.hpp
  include/ddc/kernels/splines/spline_boundary_conditions.hpp
Labels: documentation

#445 fix typo in DiscreteElement::operator--
  include/ddc/discrete_element.hpp
  tests/discrete_element.cpp
Labels: bug

#444 SplinesLinearSolver new API
  benchmarks/splines.cpp
  include/ddc/kernels/splines.hpp
  include/ddc/kernels/splines/matrix.hpp
  include/ddc/kernels/splines/spline_builder.hpp
  include/ddc/kernels/splines/spline_builder_2d.hpp
  include/ddc/kernels/splines/splines_linear_solver.hpp
  include/ddc/kernels/splines/splines_linear_solver_maker.hpp
  include/ddc/kernels/splines/splines_linear_solver_sparse.hpp
  tests/splines/matrix.cpp
Labels: enhancement

#453 Remove oldest image
  .github/workflows/tests.yml
  docker/oldest/Dockerfile
  docker/oldest/bash_run
Labels: ci

#454 Upgrade doxygen image
  docker/doxygen/Dockerfile
Labels: ci

#451 Splines linear solver dense
  CMakeLists.txt
  LICENSES/CECILL-C.txt
  cmake/FindLAPACKE.cmake
  cmake/FindLAPACKEXT.cmake
  docker/doxygen/Dockerfile
  docker/latest/Dockerfile
  docker/oldest/Dockerfile
  include/ddc/kernels/splines.hpp
  include/ddc/kernels/splines/spline_builder.hpp
  include/ddc/kernels/splines/splines_linear_problem.hpp
  include/ddc/kernels/splines/splines_linear_problem_dense.hpp
  include/ddc/kernels/splines/splines_linear_problem_maker.hpp
  include/ddc/kernels/splines/splines_linear_problem_sparse.hpp
  tests/splines/matrix.cpp
Labels: enhancement
