Repository CExA-project/ddc, pull requests merged in 2024-06, with the labels that each got.

#409 SplineBuilder doc
  include/ddc/kernels/splines/spline_builder.hpp
  include/ddc/kernels/splines/spline_builder_2d.hpp
Labels: documentation

#485 Set error on old style cast and use static_cast
  .github/workflows/tests.yml
  include/ddc/kernels/fft.hpp
  include/ddc/kernels/splines/spline_builder.hpp
  include/ddc/kernels/splines/splines_linear_problem_band.hpp
  tests/splines/batched_2d_spline_builder.cpp
  tests/splines/matrix.cpp
Labels: enhancement, ci

#486 Modernize use nullptr
  .clang-tidy
  include/ddc/kernels/fft.hpp
Labels: enhancement

#500 Doc sparse minor fix
  include/ddc/kernels/splines/splines_linear_problem_sparse.hpp
Labels: documentation

#452 Splines minor classes doc
  include/ddc/kernels/splines/greville_interpolation_points.hpp
  include/ddc/kernels/splines/knots_as_interpolation_points.hpp
Labels: documentation

#430 SplineEvaluator doc
  include/ddc/kernels/splines/null_extrapolation_rule.hpp
  include/ddc/kernels/splines/spline_evaluator.hpp
  include/ddc/kernels/splines/spline_evaluator_2d.hpp
Labels: documentation
