Repository CExA-project/ddc, pull requests merged in 2025-02, with the labels that each got.

#774 Add missing KOKKOS_FUNCTION annotation in new domains
  include/ddc/discrete_domain.hpp
  include/ddc/storage_discrete_domain.hpp
  include/ddc/strided_discrete_domain.hpp
Labels: bug

#773 Add a new initialisation function for dimensions without attributes
  examples/game_of_life.cpp
  include/ddc/ddc.hpp
  include/ddc/trivial_space.hpp
  tests/CMakeLists.txt
  tests/trivial_space.cpp
Labels: enhancement, core

#776 Update github runner to ubuntu-latest
  .github/workflows/early_integration.yml
  .github/workflows/tests.yml
Labels: ci

#771 add sycl backend
  benchmarks/splines.cpp
  cmake/DDCCheckRequiredKokkosOptions.cmake
  include/ddc/ddc.hpp
  include/ddc/detail/dual_discretization.hpp
  include/ddc/detail/macros.hpp
  include/ddc/discrete_space.hpp
  include/ddc/kernels/splines/splines_linear_problem_sparse.hpp
Labels: enhancement, core
